#!/bin/bash
width=$(tmux list-clients -F '#{client_width}')
declare -a windows
windows=( $(tmux list-windows -F '#{window_id}:#W') )
let height=$(tmux list-clients -F '#{client_height}')*2

function changelayouts()
    {
    echo "DIMENSIONS: $width x $height"
    echo "--------"
    case $1 in
	1) 
	    org="main-vertical"
	    other="even-horizontal"
	    ;;
	2)
	    org="even-vertical"
	    other="even-vertical"
	    ;;
    esac
    for window in ${windows[@]}
    do
	id="$(echo "$window" | cut -f 1 -d ":" )" 
	name="$(echo "$window" | cut -f 2 -d ":" )"
	case "$name" in 
	    org)
		tmux select-layout -t "$id" "$org"
		echo "WIN_ID:$id WIN_NAME:$name LAYOUT:$org"
		;;
	    *) 
		tmux select-layout -t "$id" "$other"
		echo "WIN_ID:$id WIN_NAME:$name LAYOUT:$other"
		;;
	esac
	echo "--------"
    done
    }

[ $width -gt $height ] && changelayouts 1 || changelayouts 2
